Repository wecode-bootcamp-korea/24-1st-DotFriends-backend, pull requests merged in 2021-09, with the labels that each got.

#1 [신우주] ADD:Models 완료
  dotfriends/settings.py
  orders/__init__.py
  orders/admin.py
  orders/apps.py
  orders/migrations/__init__.py
  orders/models.py
  orders/tests.py
  orders/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#2 [신우주] ADD: 로그인,회원가입 기능구현
  .gitignore
  dotfriends/settings.py
  dotfriends/urls.py
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  requirements.txt
  users/migrations/0001_initial.py
  users/models.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#3 [서동규]Update: 상품 뷰 수정
  .gitignore
  dotfriends/urls.py
  orders/migrations/0001_initial.py
  products/decorator.py
  products/migrations/0001_initial.py
  products/urls.py
  products/views.py
  users/migrations/0001_initial.py
Labels: Status: conflict 해결 요청

#5 [서동규] 리뷰 모델 추가 제품 모델 변경
  comments/__init__.py
  comments/admin.py
  comments/apps.py
  comments/migrations/0001_initial.py
  comments/migrations/__init__.py
  comments/models.py
  comments/tests.py
  comments/views.py
  dotfriends/settings.py
  products/migrations/0002_descriptionimage.py
  products/models.py
  products/views.py
Labels: Status: 리뷰 요청

#7 [신우주] ADD : 검색기능 추가
  dotfriends/settings.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#4 [김동준]ADD: 상품 리스트 추가
  dotfriends/urls.py
  products/views.py
Labels: Status: conflict 해결 요청

#10 [김동준] 1UPDATE : UserProductLike 모델
  products/migrations/0003_alter_userproductlike_unique_together.py
  products/models.py
Labels: Status: 리뷰 요청

#8 [서동규]Add: 상품상세페이지 API 구현
  .gitignore
  comments/models.py
  comments/urls.py
  dotfriends/settings.py
  products/decorator.py
  products/urls.py
  products/views.py
  pull_request_template.md
Labels: Status: 수정 요청, Status: conflict 해결 요청

#11 [김동준] UPDATE : visitor_decorator 추가
  products/decorator.py
Labels: Status: 리뷰 요청

#12 [서동규]Udate: 상품상세페이지 view 수정
  dotfriends/settings.py
  dotfriends/urls.py
  products/decorator.py
  products/views.py
Labels: Status: conflict 해결 요청

#14 [김동준] UPDATE : input 데코레이터 수정, listview와 productview 단일화 및 url수정
  dotfriends/urls.py
  products/decorator.py
  products/urls.py
  products/views.py
Labels: Status: Accepted

#13 [신우주 & 김동준] ADD : cartsview/post/get/delete/patch
  carts/migrations/0002_auto_20210907_1103.py
  carts/models.py
  carts/urls.py
  carts/views.py
  dotfriends/urls.py
  products/models.py
  products/urls.py
  users/decorators.py
Labels: Status: 리뷰 요청

#15 [김동준] ADD: README 파일 추가
  README.md
Labels: Status: 리뷰 요청
